### ISSUE TITLE
排版问题

### ISSUE THREAD

**Issue by ThreeSourLemon** [shizheng233/CopyMangaJava#1]
设置里已经设置为竖排  但是有些漫画会生效有些不会

**Comment by shizheng233** [comment]
> 设置里已经设置为竖排  但是有些漫画会生效有些不会

是最新的版本吗

**Comment by shizheng233** [comment]
﻿是最新的版本吗发自我的iPhone邮件客户端在 2023年3月1日，10:58，ThreeSourLemon ***@***.***> 写道：﻿
设置里已经设置为竖排  但是有些漫画会生效有些不会

**Comment by ThreeSourLemon** [comment]
> > 设置里已经设置为竖排  但是有些漫画会生效有些不会
> 
> 是最新的版本吗

是的1.0.4版本

**Comment by shizheng233** [comment]
> > > 设置里已经设置为竖排  但是有些漫画会生效有些不会
> 
> > 
> 
> > 是最新的版本吗
> 
> 
> 
> 是的1.0.4版本

明白了，大概是哪里的逻辑出了问题

**Comment by shizheng233** [comment]
> > > 设置里已经设置为竖排  但是有些漫画会生效有些不会
> 
> > 
> 
> > 是最新的版本吗
> 
> 
> 
> 是的1.0.4版本

对了，在那些没有生效的漫画里，您是否在漫画里设置过布局了？如果在漫画里修改过布局，那个漫画将会使用设置的布局

**Comment by shizheng233** [comment]
就是单个漫画会使用您在漫画里设置的布局（如果你设置过的话），不会使用主要设置里面的布局。

**Comment by ThreeSourLemon** [comment]
> 

没有设置单个漫画布局
我是第一次进入这些漫画
https://www.swisstransfer.com/d/67de4033-090c-4669-bf52-d67da1c04824
我录了个视频 你可以看看

**Comment by shizheng233** [comment]
> > 
> 
> 
> 
> 没有设置单个漫画布局
> 
> 我是第一次进入这些漫画
> 
> https://www.swisstransfer.com/d/67de4033-090c-4669-bf52-d67da1c04824
> 
> 我录了个视频 你可以看看

明白，我已经知道了，下个版本一并修复。
