### ISSUE TITLE
大佬请修复一下hacg吧

### ISSUE THREAD

**Issue by youlan2333** [shizheng233/CopyMangaJava#26]
最新网址换成了hacg.mov/wp，代码小白，尝试用mt管理器替换网址，结果详细页还是打不开

![Screenshot_20240801-151120.png](https://github.com/user-attachments/assets/76436243-6edf-4769-8f8e-a30ce57262cd)

![Screenshot_20240801-151046.png](https://github.com/user-attachments/assets/dbe3812b-0c6d-44e4-8dc3-1caa14d6791a)

![Screenshot_20240801-151042.png](https://github.com/user-attachments/assets/23a725f6-c51b-431e-a3a4-d493ddd9d290)

**Comment by shizheng233** [comment]
几次换机重装，有一次源码没有备份现在都没有了。因为怕被上门所以这个和bika都是删库了而不是改变为私有库。所以没办法咯，GitHub上不是还有几个HACG吗？

**Comment by youlan2333** [comment]
> 几次换机重装，有一次源码没有备份现在都没有了。因为怕被上门所以这个和bika都是删库了而不是改变为私有库。所以没办法咯，GitHub上不是还有几个HACG吗？

但是都不太好用😥
