### ISSUE TITLE
漫画列表无法自动翻页问题

### ISSUE THREAD

**Issue by warxj8661528** [shizheng233/CopyMangaJava#3]
漫画列表只有几个漫画在不断重复，没法自动翻页，版本1.0.4，卸载重装也没有解决

**Comment by shizheng233** [comment]
漫画列表指的是什么？最近官方的API的变了。我一直没时间搞。

**Comment by warxj8661528** [comment]
就是点击 全部漫画 后，不断下滑，漫画只有开头几个，不断重复

**Comment by shizheng233** [comment]
> 就是点击 全部漫画 后，不断下滑，漫画只有开头几个，不断重复 

我明白了。
