### ISSUE TITLE
条漫状态栏黑边问题

### ISSUE THREAD

**Issue by ShinonAzusa** [shizheng233/CopyMangaJava#4]
条漫下状态栏黑边问题希望可以优化一下，改成全屏显示

**Comment by shizheng233** [comment]
我并没发现有黑边啊。能否提供一下手机品牌、安卓版本还有系统

**Comment by ShinonAzusa** [comment]
设备是红米k50，安卓13，MIUI14.0.5

**Comment by omigugi** [comment]
![Uploading Screenshot_2023-04-04-14-25-42-739_com.shicheeng.copymanga.jpg…]()

**Comment by ShinonAzusa** [comment]
![comic](https://user-images.githubusercontent.com/105984494/229706710-c6037fef-913b-4c2d-98ba-c563d58bedae.jpg)

**Comment by shizheng233** [comment]
> 设备是红米k50，安卓13，MIUI14.0.5

这种深度定制化系统只能随缘修了，加上我是个菜鸡开发者

**Comment by ShinonAzusa** [comment]
_(:з」∠)_
