### ISSUE TITLE
作者您好，能否留个联系方式 技术交流下 谢谢

### ISSUE THREAD

**Issue by crowforkotlin** [shizheng233/CopyMangaJava#7]

**Comment by shizheng233** [comment]
就是上次问你Api的那个gmail

**Comment by crowforkotlin** [comment]
我去 我以为搞网站的那个人和你没啥联系




Crow
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shizheng233/CopyMangaJava"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月1日(星期五) 晚上9:35
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [shizheng233/CopyMangaJava] 作者您好，能否留个联系方式 技术交流下 谢谢 (Issue #7)





 
就是上次问你Api的那个gmail

**Comment by crowforkotlin** [comment]
Wechat Or QQ 留个联系方式 ？
Q:1424630050
Wechat: CrowForNothing

shizheng233 ***@***.***> 于2023年9月1日周五 21:35写道：
